<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <artifactId>ecms-core</artifactId>
    <groupId>org.exoplatform.ecms</groupId>
    <version>7.2.0-20260430</version>
  </parent>
  <artifactId>ecms-core-viewer</artifactId>
  <name>eXo PLF:: DMS Document Viewer</name>
  <description>eXo PDF Viewer</description>
  <properties>
    <exo.test.coverage.ratio>0</exo.test.coverage.ratio>
  </properties>
  <dependencies>
    <dependency>
      <groupId>javax.jcr</groupId>
      <artifactId>jcr</artifactId>
    </dependency>
    <dependency>
      <groupId>org.exoplatform.ecms</groupId>
      <artifactId>ecms-core-services</artifactId>
    </dependency>
    <dependency>
      <groupId>io.meeds.kernel</groupId>
      <artifactId>exo.kernel.container</artifactId>
    </dependency>
    <dependency>
      <groupId>io.meeds.portal</groupId>
      <artifactId>portal.component.resources</artifactId>
    </dependency>
    <dependency>
      <groupId>io.meeds.portal</groupId>
      <artifactId>portal.component.web.resources</artifactId>
    </dependency>
    <dependency>
      <groupId>io.meeds.portal</groupId>
      <artifactId>portal.webui.portal</artifactId>
    </dependency>
    <dependency>
      <groupId>org.icepdf.os</groupId>
      <artifactId>icepdf-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.exoplatform.ecms</groupId>
      <artifactId>ecms-social-integration</artifactId>
    </dependency>
    <dependency>
      <groupId>org.exoplatform.ecms</groupId>
      <artifactId>ecms-core-connector</artifactId>
    </dependency>

    <dependency>
      <groupId>org.exoplatform.ecms</groupId>
      <artifactId>ecms-testsuite-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.meeds.portal</groupId>
      <artifactId>portal.component.identity</artifactId>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.meeds.portal</groupId>
      <artifactId>portal.component.portal</artifactId>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.meeds.portal</groupId>
      <artifactId>portal.component.test.core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.meeds.portal</groupId>
      <artifactId>portal.component.test.web</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.meeds.commons</groupId>
      <artifactId>commons-component-common</artifactId>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.meeds.social</groupId>
      <artifactId>social-component-core</artifactId>
      <scope>test</scope>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>org.exoplatform.ecms</groupId>
      <artifactId>ecms-core-services</artifactId>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <resources>
      <!-- We need to filter only properties files -->
      <resource>
        <filtering>true</filtering>
        <directory>src/main/resources</directory>
        <includes>
          <include>**/*.properties</include>
        </includes>
      </resource>
      <resource>
        <directory>src/main/resources</directory>
        <excludes>
          <exclude>**/*.properties</exclude>
        </excludes>
      </resource>
    </resources>
  </build>
</project>
