#
# Your Crowdin credentials
#
"project_id_env" : "CROWDIN_PROJECT_ID"
"api_token_env" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true
#
# Files configuration
#
files: [
  {
    "source" : "/core/connector/src/main/resources/locale/services/fckeditor/FCKConnector_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "platform/ecms/core/FCKConnector.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/core/viewer/src/main/resources/locale/portlet/viewer/PDFViewer_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "platform/ecms/PDFViewer.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/core/connector/src/main/resources/locale/wcm/resources/WCMResourceBundleConnector_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "platform/ecms/core/WCMResourceBundleConnector.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/core/viewer/src/main/resources/locale/clouddrive/CloudDrive_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "platform/ecms/core/CloudDrive.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/apps/portlet-documents/src/main/resources/locale/portlet/documents_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "platform/ecms/apps/documents.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/apps/portlet-documents/src/main/resources/locale/portlet/ckeditor_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "platform/ecms/apps/ckeditor.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/apps/portlet-documents/src/main/resources/locale/portlet/attachments_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "platform/ecms/apps/attachments.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/apps/portlet-documents/src/main/resources/locale/portal/webui_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "platform/ecms/apps/webui.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/apps/portlet-transferrules/src/main/resources/locale/portlet/transferRules_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "platform/ecms/portlet-transfer-rules/portlets.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/apps/portlet-documents/src/main/resources/locale/portlet/Analytics_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "platform/ecms/Analytics.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/ecms-social-integration/src/main/resources/locale/extension/SocialIntegration_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "platform/ecms/SocialIntegration.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  }
]
