name: Sonar Analysis
on:
  push:
    branches: [ stable/6.5.x ]
  pull_request:
jobs:
  sonar-analysis:
    name: Analyse Project with SonarCloud 
    runs-on: ubuntu-latest
    steps:
      - name: Analyse Project
        uses: exo-actions/sonarcloud-action@v1
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}